### ISSUE TITLE
Fix unknown issue with Ristretto encoding

### ISSUE THREAD

**Issue by isislovecruft** [isislovecruft/ristretto-donna#1]
The Ristretto encoding tests aren't passing, cf. `test_ristretto_encode_basepoint()` and `test_ristretto_encode_small_multiples_of_basepoint()`. However, the test for the donna functions to "unpack" (i.e. expand) and "pack" (i.e. contract) a "`ge25519`" (i.e. a point) in `test_ge25519_unpack_pack()` also aren't passing, which is probably related and should be investigated first.

**Comment by isislovecruft** [comment]
Hmm. Doing the following:

```C
result = ge25519_unpack_negative_vartime(&a, IDENTITY);
ge25519_pack(b, &a);
```

results in `b = { 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 80 }`. (Note the 0x80 at the end, rather than 0x00.)

**Comment by isislovecruft** [comment]
Oh god fucking dammit. It's setting a parity bit.

```C
static void
ge25519_pack(unsigned char r[32], const ge25519 *p) {
	bignum25519 tx, ty, zi;
	unsigned char parity[32];
	curve25519_recip(zi, p->z);
	curve25519_mul(tx, p->x, zi);
	curve25519_mul(ty, p->y, zi);
	curve25519_contract(r, ty);
	curve25519_contract(parity, tx);
	r[31] ^= ((parity[0] & 1) << 7);
}
```

**Comment by isislovecruft** [comment]
Alright, we've now got our own custom element contraction function and the test passes. Something's still wrong with the Ristretto encoding however.

**Comment by isislovecruft** [comment]
So encoding and then decoding the identity point works, but not the Ristretto basepoint. My irking suspicion is that the problem lies with the field elements not being reduced properly, so I'm going to try the super hacky thing of contracting-then-expanding between all mul operations.

**Comment by TerenceGe** [comment]
@isislovecruft Hello, I'm using this library in my project and fix some issues in the encoding method. Just sent a pr for this. Can you check https://github.com/isislovecruft/ristretto-donna/pull/4

**Comment by isislovecruft** [comment]
Thanks @TerenceGe! You found it! Merged and fixed.

**Comment by isislovecruft** [comment]
For the record, the bug was that I was missing a squaring in the encoding. I've carefully re-reviewed the code against our RFC and the algorithms match now, and the code matches test vectors.
